import Decimal from "break_eternity.js";
import { CachedPlayer, Player } from "./playerTypes";

export function getDefaultPlayer(): Player {
  const defaultPlayer: Player = {
    gameVersion: "0.5.2",
    lastTick: Date.now(),
    points: new Decimal(0),
    upgradeLvl: new Decimal(0),
    startedRun: Date.now(),
    approximateResetsPerSecond: new Decimal(0),
    bestRun: null,
    everMadeRun: false,
    autoresettingEnabled: true,
    bestPointsOfRun: new Decimal(0),
    boughtFirstResetUpgrade: false,
    boughtSecondResetUpgrade: false,
    everMadeTier: false,
    tier: new Decimal(0),
    madeTierTimes: new Decimal(0),
    approximateTiersPerSecond: new Decimal(0),
    autoTierEnabled: true,
    boughtFirstTierUpgrade: false,
    boughtSecondTierUpgrade: false,
    boughtThirdTierUpgrade: false,
    boughtFourthTierUpgrade: false,
    tierStartedDate: null,
    ampliflux: new Decimal(0),
    amplifluxUpgradeLvl: new Decimal(0),
    boughtFifthTierUpgrade: false,
    boughtSixthTierUpgrade: false,
    everMadeVermyros: false,
    vermyrosStartedDate: null,
    approximateVermyrosResetsPerSecond: new Decimal(0),
    autoVermyrosEnabled: true,
    vermytes: new Decimal(0),
    bestVermytes: new Decimal(0),
    vermytesUpgradeLvl: new Decimal(0),
    vermora: new Decimal(0),
    boughtFirstVermyrosUpgrade: false,
    boughtSecondVermyrosUpgrade: false,
    boughtThirdVermyrosUpgrade: false,
    boughtFourthVermyrosUpgrade: false,
    boughtFifthVermyrosUpgrade: false,
    boughtSixthVermyrosUpgrade: false,
    boughtSeventhVermyrosUpgrade: false,
    boughtEighthVermyrosUpgrade: false,
    enteredAmplivault: false,
    amplivaultLevel: new Decimal(0),
    bestSoftcapperLevel: new Decimal(0),
    stableProgressBars: true,
    energyReactors: new Decimal(0),
    energy: new Decimal(0),
    everReachedCores: false,
    everMadeCoreReset: false,
    cores: new Decimal(0),
    coreUpgradeLvl: new Decimal(0),
    boughtNinthVermyrosUpgrade: false,
    boughtTenthVermyrosUpgrade: false,
    everBoughtTenthVermyrosUpgrade: false,
    exponentialNotation: false,
    darkEnergy: new Decimal(0),
    everMadeNullith: false,
    nullithStartedDate: null,
    autoNullithEnabled: true,
    madeNullithResets: new Decimal(0),
    approximateNullithResetsPerSecond: new Decimal(0),
    boughtFirstNullithUpgrade: false,
    boughtSecondNullithUpgrade: false,
    boughtThirdNullithUpgrade: false,
    boughtFourthNullithUpgrade: false,
    hideBoughtUpgrades: false,
    reachedBreakAmplivault: false,
    amplivaultBroken: false,
    nullionInput: "",
    nullions: new Decimal(0),
    boughtFifthNullithUpgrade: false,
    boughtSixthNullithUpgrade: false,
    enteredSliph: false,
    everEnteredSliph: false,
    dertoints: new Decimal(0),
    dertointUpgradeLvl: new Decimal(0),
    boughtFirstDertointUpgrade: false,
    boughtSecondDertointUpgrade: false,
    boughtThirdDertointUpgrade: false,
    boughtFourthDertointUpgrade: false,
    boughtFirstMallirtUpgrade: false,
    boughtSecondMallirtUpgrade: false,
    boughtThirdMallirtUpgrade: false,
    boughtFourthMallirtUpgrade: false,
    everMadeMallirt: false,
    mallirtStartedDate: null,
    autoMallirtEnabled: true,
    approximateMallirtResetsPerSecond: new Decimal(0),
    mallirtTotalDertoints: new Decimal(0)
  };
  return defaultPlayer;
}

export function getDefaultCachedPlayer(): CachedPlayer {
  const defaultCachedPlayer: CachedPlayer = {
    pointGain: new Decimal(1),
    timeSinceHighestReset: 0,
    upgradeCost: new Decimal(0),
    upgradeEffect: new Decimal(1),
    upgradeBulk: new Decimal(0),
    lastResetTime: null,
    runEffect: new Decimal(1),
    bestPointsOfRunEffect: new Decimal(1),
    lastTierTime: null,
    tierRequirement: new Decimal(Infinity),
    tierResetGain: new Decimal(0),
    tierEffect: new Decimal(1),
    tierTimesEffect: new Decimal(1),
    amplifluxGain: new Decimal(1),
    amplifluxEffect: new Decimal(1),
    amplifluxUpgradeCost: new Decimal(0),
    amplifluxUpgradeEffect: new Decimal(1),
    amplifluxUpgradeBulk: new Decimal(0),
    lastVermyrosTime: null,
    vermytesGain: new Decimal(0),
    vermytesBestEffect: new Decimal(1),
    vermytesUpgradeCost: new Decimal(0),
    vermytesUpgradeEffect: new Decimal(1),
    vermytesUpgradeBulk: new Decimal(0),
    vermoraGain: new Decimal(0),
    vermoraEffect: new Decimal(1),
    vermytesPerSecond: new Decimal(0),
    amplivaultRequirement: new Decimal(Infinity),
    amplivaultEffect: new Decimal(1),
    softcapperLevel: new Decimal(0),
    energyReactorGain: new Decimal(0),
    energyGain: new Decimal(0),
    energyEffect: new Decimal(1),
    coreGain: new Decimal(0),
    coreEffect: new Decimal(0),
    coreUpgradeCost: new Decimal(0),
    coreUpgradeEffect: new Decimal(1),
    coreUpgradeBulk: new Decimal(0),
    darkEnergyGain: new Decimal(0),
    darkEnergyEffect: new Decimal(1),
    lastNullithTime: null,
    nullithResetGain: new Decimal(0),
    nullithResetsEffect: new Decimal(1),
    nullithResetsVermyteEffect: new Decimal(1),
    nullithResetsEnergyEffect: new Decimal(1),
    coresPerSecond: new Decimal(0),
    isCoreUpgradeMaxed: false,
    nullionGain: new Decimal(0),
    nullionEffect: new Decimal(1),
    nullionInputConverted: new Decimal(0),
    dertointGain: new Decimal(0),
    dertointEffect: new Decimal(1),
    dertointUpgradeCost: new Decimal(0),
    dertointUpgradeBulk: new Decimal(0),
    dertointUpgradeEffect: new Decimal(1),
    firstDertointUpgradeEffect: new Decimal(1),
    lastMallirtTime: null,
    mallirtEffect: new Decimal(1)
  };
  return defaultCachedPlayer;
}
