import Decimal from "break_eternity.js";
import { Settings } from "./playerTypes";

export const settings: Settings = {
  localStorageName: "PointsProgression",
  saveInterval: 10000,
  upgradeStartingCost: new Decimal(10),
  upgradeScaling: new Decimal(1.2),
  upgradeEffectScaling: new Decimal(1.125),
  firstResetLayerGoal: new Decimal(1e6),
  bestRunTimeLimit: 10,
  resetFirstUpgradeCost: new Decimal(1e20),
  resetSecondUpgradeCost: new Decimal(1e23),
  firstTierAt: new Decimal(1e25),
  tierScaling: new Decimal(1000),
  firstTierUpgradeCost: new Decimal(1e27),
  secondTierUpgradeCost: new Decimal(1e32),
  thirdTierUpgradeCost: new Decimal(1e40),
  fourthTierUpgradeCost: new Decimal(1e62),
  amplifluxUpgradeStartingCost: new Decimal(10),
  amplifluxUpgradeCostScaling: new Decimal(1.15),
  amplifluxUpgradeEffectScaling: new Decimal(1.1),
  fifthTierUpgradeCost: new Decimal(1e74),
  sixthTierUpgradeCost: new Decimal(1e82),
  vermyrosGoal: new Decimal(1e84),
  vermytesUpgradeStartingCost: new Decimal(1),
  vermytesUpgradeCostScaling: new Decimal(2),
  vermytesUpgradeEffectScaling: new Decimal(3),
  firstVermyrosUpgradeCost: new Decimal(1),
  secondVermyrosUpgradeCost: new Decimal(1e90),
  thirdVermyrosUpgradeCost: new Decimal(1e96),
  fourthVermyrosUpgradeCost: new Decimal(1e114),
  fifthVermyrosUpgradeCost: new Decimal(1e133),
  sixthVermyrosUpgradeCost: new Decimal(1e162),
  seventhVermyrosUpgradeCost: new Decimal(1e186),
  eighthVermyrosUpgradeCost: new Decimal(1e212),
  amplivaultRequirementStartsAt: new Decimal(1e30),
  softcappers: [
    [new Decimal(1e204), new Decimal(0.94)],
    [new Decimal("1e368"), new Decimal(0.85)],
    [new Decimal("1e1000"), new Decimal(0.5)]
  ],
  coresAt: new Decimal(1e6),
  coreUpgradeStartingCost: new Decimal(10),
  coreUpgradeCostScaling: new Decimal(10),
  coreUpgradeEffectScaling: new Decimal(1.1),
  ninthVermyrosUpgradeCost: new Decimal(1e230),
  tenthVermyrosUpgradeCost: new Decimal(1e250),
  nullithGoal: new Decimal(2).pow(1024),
  firstNullithUpgradeCost: new Decimal(49674),
  secondNullithUpgradeCost: new Decimal("7.438e323"),
  thirdNullithUpgradeCost: new Decimal("1.905e375"),
  fourthNullithUpgradeCost: new Decimal("9.064e435"),
  maxCoreUpgradeLevel: new Decimal(40),
  stableProgressBarsStartWorkingAt: 6,
  fifthNullithUpgradeCost: new Decimal("1e1000"),
  sixthNullithUpgradeCost: new Decimal("1e1150"),
  dertointUpgradeStartingCost: new Decimal(0.1),
  dertointUpgradeCostScaling: new Decimal(10),
  dertointUpgradeEffectScaling: new Decimal(2.4),
  firstDertointUpgradeCost: new Decimal(100),
  secondDertointUpgradeCost: new Decimal(7.5e3),
  thirdDertointUpgradeCost: new Decimal(8.25e4),
  fourthDertointUpgradeCost: new Decimal(9e5),
  firstMallirtUpgradeCost: new Decimal(5.5e6),
  secondMallirtUpgradeCost: new Decimal(2.7e7),
  thirdMallirtUpgradeCost: new Decimal(7.435e11),
  fourthMallirtUpgradeCost: new Decimal(3.21e13),
  mallirtGoal: new Decimal(1e6),
  endgameAt: new Decimal("1e1150")
} as const;
